#!/bin/bash

if [ $# -lt 1 ]; then
    >&2 echo "Needs 1 parameter (db_name)"
    exit 1
fi

root="$HOME/Dev/odoo"
dir="$PWD"
while [[ "$dir" == "$root" || "$dir" == "$root"/* ]]; do
    if [ -f "$dir/.wtenv" ]; then
        if grep -q '^db=' "$dir/.wtenv"; then
            sed -i '' "s|^db=.*|db=$1|" "$dir/.wtenv"
        else
            echo "db=$1" >> "$dir/.wtenv"
        fi
        echo "$1 (workspace ${dir##*/})"
        exit 0
    fi
    dir=$(dirname "$dir")
done

[[ -f "$HOME/.odoorc" ]] && sed -i '' "s/db_name =.*/db_name = $1/g" "$HOME/.odoorc"
echo "$1" > "$HOME/.current_db"
